#!/bin/sh

should_auto_checkout() {
    [ -f "auto_checkout" ]
}

should_auto_checkout || exit 0

# Kludge to read the last ref
while read old new ref; do
    real_sha=$new
done

export GIT_WORK_TREE=$PWD/../
git checkout -qf $real_sha &&
    echo "Checked out $real_sha"
